### ISSUE TITLE
InversionFilter::rebuildCache

### ISSUE THREAD

**Issue by tiber2** [inphos42/osmpbf#8]
InversionFilter::rebuildCache should always return true since if the child filter does match anything (rebuildCache  returns false), the inversion filter matches everything.

**Comment by tiber2** [comment]
Hello dbahrdt,

Thanks for the fix but I warn you that you introduce a new bug. Calling rebuildCache on child node is necessary.

**Comment by dbahrdt** [comment]
Hi, thanks for the hint. It really is not a good idea to fix stuff right before going to lunch.
